cross_target_platform:
  - linux-64                            # [linux]
  - linux-aarch64                       # [linux]
  - linux-ppc64le                       # [linux]
  - linux-riscv64                       # [linux]
  - osx-64                              # [unix]
  - osx-arm64                           # [unix]
  - win-64                              # [linux64 or win]
  - win-arm64                           # [linux64 or win]
GOOS:
  - linux                               # [linux]
  - linux                               # [linux]
  - linux                               # [linux]
  - linux                               # [linux]
  - darwin                              # [unix]
  - darwin                              # [unix]
  - windows                             # [linux64 or win]
  - windows                             # [linux64 or win]
GOARCH:
  - amd64                               # [linux]
  - arm64                               # [linux]
  - ppc64le                             # [linux]
  - riscv64                             # [linux]
  - amd64                               # [unix]
  - arm64                               # [unix]
  - amd64                               # [linux64 or win]
  - arm64                               # [linux64 or win]
go_variant_str:
  - cgo
  - nocgo
zip_keys:
  -
    - cross_target_platform
    - GOOS
    - GOARCH
